#!/usr/bin/env bash
# Shared helpers for deploy/*.sh — source after loading secrets.env
set -euo pipefail

DEPLOY_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$DEPLOY_DIR/.." && pwd)"

load_secrets() {
  local f="${DEPLOY_SECRETS:-$DEPLOY_DIR/secrets.env}"
  if [[ ! -f "$f" ]]; then
    echo "Missing $f — copy deploy/secrets.env.example → deploy/secrets.env" >&2
    exit 1
  fi
  set -a
  # shellcheck disable=SC1090
  source "$f"
  set +a
  : "${MUSIK_SSH_HOST:?}"
  : "${MUSIK_SSH_USER:?}"
  : "${MUSIK_REMOTE_ROOT:?}"
  : "${MUSIK_REMOTE_LIBRARY:?}"
}

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "Need '$1' installed on this machine" >&2
    exit 1
  }
}

# Prefer rsync; fall back to tar|ssh (no rsync required on laptop).
sync_dir_to_remote() {
  local src="$1" dest="$2" # src local dir, dest remote absolute dir
  src="${src%/}"
  if command -v rsync >/dev/null 2>&1; then
    export SSHPASS="${MUSIK_SSH_PASS:-}"
    local RSH
    RSH="$(rsync_ssh)"
    remote "mkdir -p ${dest}"
    rsync -avh --progress -e "$RSH" \
      --exclude '.DS_Store' --exclude '@eaDir/' \
      "$src/" "${MUSIK_SSH_USER}@${MUSIK_SSH_HOST}:${dest}/"
    return
  fi
  echo "rsync missing — using tar|ssh"
  remote "mkdir -p ${dest}"
  local key="$DEPLOY_DIR/.ssh/id_ed25519"
  local opts=(-o StrictHostKeyChecking=accept-new -o ConnectTimeout=10)
  if [[ -f "$key" ]]; then
    opts+=(-i "$key" -o IdentitiesOnly=yes)
    tar -C "$src" -cf - . | ssh "${opts[@]}" "${MUSIK_SSH_USER}@${MUSIK_SSH_HOST}" \
      "tar -C ${dest} -xf -"
  else
    echo "Need deploy key for tar|ssh" >&2
    exit 1
  fi
}

remote() {
  local key="$DEPLOY_DIR/.ssh/id_ed25519"
  local opts=(-o StrictHostKeyChecking=accept-new -o ConnectTimeout=10)
  if [[ -f "$key" ]]; then
    opts+=(-i "$key" -o IdentitiesOnly=yes)
    if [[ $# -eq 1 ]]; then
      ssh "${opts[@]}" "${MUSIK_SSH_USER}@${MUSIK_SSH_HOST}" "$1"
    else
      ssh "${opts[@]}" "${MUSIK_SSH_USER}@${MUSIK_SSH_HOST}" "$@"
    fi
    return
  fi
  if [[ -f "$DEPLOY_DIR/py_ssh.py" && -d "$DEPLOY_DIR/.vendor" ]]; then
    export MUSIK_SSH_HOST MUSIK_SSH_USER MUSIK_SSH_PASS
    local cmd
    if [[ $# -eq 1 ]]; then
      cmd="$1"
    else
      printf -v cmd '%q ' "$@"
    fi
    python3 "$DEPLOY_DIR/py_ssh.py" run "$cmd"
    return
  fi
  if [[ -n "${MUSIK_SSH_PASS:-}" ]] && command -v sshpass >/dev/null 2>&1; then
    if [[ $# -eq 1 ]]; then
      SSHPASS="$MUSIK_SSH_PASS" sshpass -e ssh "${opts[@]}" \
        -o PreferredAuthentications=password -o PubkeyAuthentication=no \
        "${MUSIK_SSH_USER}@${MUSIK_SSH_HOST}" "$1"
    else
      SSHPASS="$MUSIK_SSH_PASS" sshpass -e ssh "${opts[@]}" \
        -o PreferredAuthentications=password -o PubkeyAuthentication=no \
        "${MUSIK_SSH_USER}@${MUSIK_SSH_HOST}" "$@"
    fi
    return
  fi
  echo "No deploy/.ssh/id_ed25519. Run: ./deploy/ssh-key-setup.sh" >&2
  exit 1
}

# For heredocs: remote_bash <<'EOF' ... EOF
remote_bash() {
  local key="$DEPLOY_DIR/.ssh/id_ed25519"
  local opts=(-o StrictHostKeyChecking=accept-new -o ConnectTimeout=10)
  if [[ -f "$key" ]]; then
    opts+=(-i "$key" -o IdentitiesOnly=yes)
    ssh "${opts[@]}" "${MUSIK_SSH_USER}@${MUSIK_SSH_HOST}" bash -s
    return
  fi
  if [[ -n "${MUSIK_SSH_PASS:-}" ]] && command -v sshpass >/dev/null 2>&1; then
    SSHPASS="$MUSIK_SSH_PASS" sshpass -e ssh "${opts[@]}" \
      -o PreferredAuthentications=password -o PubkeyAuthentication=no \
      "${MUSIK_SSH_USER}@${MUSIK_SSH_HOST}" bash -s
    return
  fi
  echo "Need key or sshpass for remote_bash" >&2
  exit 1
}

rsync_ssh() {
  local key="$DEPLOY_DIR/.ssh/id_ed25519"
  if [[ -f "$key" ]]; then
    echo "ssh -i $key -o StrictHostKeyChecking=accept-new -o IdentitiesOnly=yes"
    return
  fi
  if [[ -n "${MUSIK_SSH_PASS:-}" ]] && command -v sshpass >/dev/null 2>&1; then
    echo "sshpass -e ssh -o StrictHostKeyChecking=accept-new -o PreferredAuthentications=password -o PubkeyAuthentication=no"
    return
  fi
  echo "Need ./deploy/ssh-key-setup.sh (key) for rsync, or install sshpass" >&2
  exit 1
}

public_base_url() {
  local scheme="${MUSIK_PUBLIC_SCHEME:-https}"
  local domain="${MUSIK_DOMAIN:?set MUSIK_DOMAIN in secrets.env}"
  echo "${scheme}://${domain}"
}

write_remote_env() {
  local out="$1"
  local base
  base="$(public_base_url)"
  cat >"$out" <<EOF
# Generated by deploy scripts — do not commit
MUSIK_PASSWORD=${MUSIK_PASSWORD:?}
MUSIK_API_TOKEN=${MUSIK_API_TOKEN:?}
MUSIK_SESSION_SECRET=${MUSIK_SESSION_SECRET:?}
MUSIK_LIBRARY=${MUSIK_REMOTE_LIBRARY}
MUSIK_PUBLIC_BASE_URL=${base}
MUSIK_SECURE_COOKIE=$([ "${MUSIK_PUBLIC_SCHEME:-https}" = https ] && echo 1 || echo 0)
MUSIK_TASTE_ALPHA=0.22
MUSIK_PROFILE_FORMING_AT=3
MUSIK_PROFILE_READY_AT=8
MUSIK_EXPLORE_RATIO=0.15
MUSIK_DISCOVER_EXPLORE=0.35
MUSIK_QUEUE_SIZE=6
MUSIK_SHARE_MAX_LISTENERS=4
EOF
}
